server:
    port: 8080
    context-path: /
    tomcat:
        uri-encoding: UTF-8

spring:

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

      #file upload size config
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
    datasource:
        druid:
            url: jdbc:mysql://127.0.0.1:3306/jc_apply?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&idleConnectionTestPeriod=120&preferredTestQuery=select now()&allowMultiQueries=true
            username: root
            password: admin
            initial-size: 1
            min-idle: 1
            max-active: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            poolPreparedStatements: false
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat
    redis:
            host: 127.0.0.1
            port: 6379
            database: 1
            password:
            timeout: 120000
            pool:
                #池中可借的最大数
                max-active: 120
                #允许池中空闲的最大连接数
                max-idle: 30
                #获取连接最大等待时间（毫秒）
                max-wait: 12000
                #允许池中空闲的最小连接数
                min-idle: 0
mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.jc.util.mybatis.MyMapper
    not-empty: false
    identity: MYSQL

swagger:
    enable: true
    baseUrl: /